apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    service: dvdrental
    tags.datadoghq.com/env: 'dev'
    tags.datadoghq.com/service: 'dvdrental'
    tags.datadoghq.com/version: '1.0'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        service: dvdrental
        tags.datadoghq.com/env: 'dev'
        tags.datadoghq.com/service: 'dvdrental'
        tags.datadoghq.com/version: '1.0'
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/js-lib.version: v5.50.0
        ad.datadoghq.com/api.logs: '[{"source": "nodejs", "service": "dvdrental"}]'
    spec:
      containers:
        - name: api
          image: docker.io/juliomourajr92/dvdrentalback:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "juliodocker"
            - name: DB_PASS
              value: "moura"
            - name: DB_NAME
              value: "dvdrental2024"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_LOGS_INJECTION
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30020
  selector:
    app: api
  type: NodePort