apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    service: bancodedados
  annotations:
    ad.datadoghq.com/postgres.logs: '[{"source": "postgres", "service": "bancodedados"}]'
    ad.datadoghq.com/postgres.checks: |
      {
        "postgres": {
          "instances": [
            {
              "host": "%%host%%",
              "port": "5432",
              "username": "juliodocker",
              "password": "moura",
              "dbname": "dvdrental2024"
            }
          ]
        }
      }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        service: bancodedados
        tags.datadoghq.com/env: 'dev'
        tags.datadoghq.com/service: 'bancodedados'
        tags.datadoghq.com/version: '1.0'
        app: postgres
      annotations:
        ad.datadoghq.com/postgres.logs: '[{"source": "postgres", "service": "bancodedados"}]'
        ad.datadoghq.com/postgres.checks: |
          {
            "postgres": {
              "instances": [
                {
                  "host": "%%host%%",
                  "port": "5432",
                  "username": "juliodocker",
                  "password": "moura",
                  "dbname": "dvdrental2024"
                }
              ]
            }
          }
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USERNAME
              value: "juliodocker"
            - name: POSTGRESQL_PASSWORD
              value: "moura"
            - name: POSTGRESQL_DATABASE
              value: "dvdrental2024"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP